<a href="https://colab.research.google.com/github/Vishwas02mehta/Vishwas-UCS420-/blob/main/assignment4que5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

ucs420_Vishwas = np.array([[10, 20, 30, 40],
                          [50, 60, 70, 80],
                          [90, 15, 20, 35]])

mean_value = np.mean(ucs420_Vishwas)
median_value = np.median(ucs420_Vishwas)
max_value = np.max(ucs420_Vishwas)
min_value = np.min(ucs420_Vishwas)
unique_elements = np.unique(ucs420_Vishwas)

reshaped_ucs420 = ucs420_Vishwas.reshape(4, 3)

print("Original 2D Array:\n", ucs420_Vishwas)
print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique Elements:", unique_elements)
print("Reshaped Array (4x3):\n", reshaped_ucs420)

Original 2D Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
